# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Use the appropriate Java version for your project
          distribution: 'temurin'

      - name: Create properties file
        run: |
          echo "gpr.usr=${{ secrets.GPR_USR }}" > secrets.properties
          echo "gpr.key=${{ secrets.GPR_KEY }}" >> secrets.properties
          echo "version.name=${{ secrets.VERSION_NAME }}" >> secrets.properties
          echo "version.code=${{ secrets.VERSION_CODE }}" >> secrets.properties
          echo "artifact.id=${{ secrets.ARTIFACT_ID }}" >> secrets.properties
          echo "group.id=${{ secrets.GROUP_ID }}" >> secrets.properties
          echo "lib.type=${{ secrets.LIB_TYPE }}" >> secrets.properties
          echo "repo.url=${{ secrets.REPO_URL }}" >> secrets.properties
          echo "maven.url=${{ secrets.MAVEN_URL }}" >> secrets.properties

      - name: Build project
        run: ./gradlew clean :foldablechecklibrary:assembleRelease  # Replace with your build command

      - name: Publish to GitHub Packages
        run: ./gradlew clean :foldablechecklibrary:assembleRelease publish  # Replace with your publish command
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
